class Solution {

        public int[] maxNumber(int[] nums1, int[] nums2, int k) {

                int[] answer = new int[k];

                        for (int i = 0; i <= k; i++) {

                                    int j = k - i;

                                                if (i > nums1.length || j > nums2.length)
                                                                continue;

                                                                            int[] a = maxSubsequence(nums1, i);
                                                                                        int[] b = maxSubsequence(nums2, j);

                                                                                                    int[] merged = merge(a, b);

                                                                                                                if (greater(merged, 0, answer, 0))
                                                                                                                                answer = merged;
                                                                                                                                        }

                                                                                                                                                return answer;
                                                                                                                                                    }

                                                                                                                                                        private int[] maxSubsequence(int[] nums, int k) {

                                                                                                                                                                int[] stack = new int[k];
                                                                                                                                                                        int top = 0;

                                                                                                                                                                                int remove = nums.length - k;

                                                                                                                                                                                        for (int num : nums) {

                                                                                                                                                                                                    while (top > 0 &&
                                                                                                                                                                                                                       stack[top - 1] < num &&
                                                                                                                                                                                                                                          remove > 0) {

                                                                                                                                                                                                                                                          top--;
                                                                                                                                                                                                                                                                          remove--;
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                  if (top < k) {
                                                                                                                                                                                                                                                                                                                  stack[top++] = num;
                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                              remove--;
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                          return stack;
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                  private int[] merge(int[] a, int[] b) {

                                                                                                                                                                                                                                                                                                                                                                                          int[] result = new int[a.length + b.length];

                                                                                                                                                                                                                                                                                                                                                                                                  int i = 0;
                                                                                                                                                                                                                                                                                                                                                                                                          int j = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                  int r = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                          while (i < a.length || j < b.length) {

                                                                                                                                                                                                                                                                                                                                                                                                                                      if (greater(a, i, b, j))
                                                                                                                                                                                                                                                                                                                                                                                                                                                      result[r++] = a[i++];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  result[r++] = b[j++];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          private boolean greater(int[] a, int i,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      int[] b, int j) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              while (i < a.length && j < b.length &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             a[i] == b[j]) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         i++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     j++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return j == b.length ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (i < a.length && a[i] > b[j]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
}