class Solution {
        public boolean canFinish(int numCourses, int[][] prerequisites) {
                List<List<Integer>> g = new ArrayList<>();
                        for (int i = 0; i < numCourses; i++) g.add(new ArrayList<>());
                                for (int[] p : prerequisites) g.get(p[1]).add(p[0]);
                                        boolean[] onStack = new boolean[numCourses];
                                                boolean[] seen = new boolean[numCourses];
                                                        for (int i = 0; i < numCourses; i++) {
                                                                    if (seen[i]) continue;
                                                                                if (!acyclic(i, g, onStack, seen)) return false;
                                                                                        }
                                                                                                return true;
                                                                                                    }

                                                                                                        private boolean acyclic(int start, List<List<Integer>> g, boolean[] onStack, boolean[] seen) {
                                                                                                                Deque<Integer> stack = new ArrayDeque<>();
                                                                                                                        Deque<Integer> idx = new ArrayDeque<>();
                                                                                                                                stack.push(start);
                                                                                                                                        idx.push(0);
                                                                                                                                                onStack[start] = seen[start] = true;
                                                                                                                                                        while (!stack.isEmpty()) {
                                                                                                                                                                    int node = stack.peek();
                                                                                                                                                                                List<Integer> children = g.get(node);
                                                                                                                                                                                            if (idx.peek() < children.size()) {
                                                                                                                                                                                                            int pos = idx.pop();
                                                                                                                                                                                                                            int child = children.get(pos);
                                                                                                                                                                                                                                            idx.push(pos + 1);
                                                                                                                                                                                                                                                            if (onStack[child]) return false;
                                                                                                                                                                                                                                                                            if (seen[child]) continue;
                                                                                                                                                                                                                                                                                            onStack[child] = seen[child] = true;
                                                                                                                                                                                                                                                                                                            stack.push(child);
                                                                                                                                                                                                                                                                                                                            idx.push(0);
                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                        onStack[node] = false;
                                                                                                                                                                                                                                                                                                                                                                        stack.pop();
                                                                                                                                                                                                                                                                                                                                                                                        idx.pop();
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                        
}